const tulind = require('tulind');

console.log(tulind.indicators);

/* All Tulind Indicators
{ abs: 
    { name: 'abs',
      full_name: 'Vector Absolute Value',
      type: 'simple',
      inputs: 1,
      options: 0,
      outputs: 1,
      input_names: [ 'real' ],
      option_names: [],
      output_names: [ 'abs' ],
      indicator: [Function],
      start: [Function] },
   acos: 
    { name: 'acos',
      full_name: 'Vector Arccosine',
      type: 'simple',
      inputs: 1,
      options: 0,
      outputs: 1,
      input_names: [ 'real' ],
      option_names: [],
      output_names: [ 'acos' ],
      indicator: [Function],
      start: [Function] },
   ad: 
    { name: 'ad',
      full_name: 'Accumulation/Distribution Line',
      type: 'indicator',
      inputs: 4,
      options: 0,
      outputs: 1,
      input_names: [ 'high', 'low', 'close', 'volume' ],
      option_names: [],
      output_names: [ 'ad' ],
      indicator: [Function],
      start: [Function] },
   add: 
    { name: 'add',
      full_name: 'Vector Addition',
      type: 'simple',
      inputs: 2,
      options: 0,
      outputs: 1,
      input_names: [ 'real', 'real' ],
      option_names: [],
      output_names: [ 'add' ],
      indicator: [Function],
      start: [Function] },
   adosc: 
    { name: 'adosc',
      full_name: 'Accumulation/Distribution Oscillator',
      type: 'indicator',
      inputs: 4,
      options: 2,
      outputs: 1,
      input_names: [ 'high', 'low', 'close', 'volume' ],
      option_names: [ 'short period', 'long period' ],
      output_names: [ 'adosc' ],
      indicator: [Function],
      start: [Function] },
   adx: 
    { name: 'adx',
      full_name: 'Average Directional Movement Index',
      type: 'indicator',
      inputs: 3,
      options: 1,
      outputs: 1,
      input_names: [ 'high', 'low', 'close' ],
      option_names: [ 'period' ],
      output_names: [ 'dx' ],
      indicator: [Function],
      start: [Function] },
   adxr: 
    { name: 'adxr',
      full_name: 'Average Directional Movement Rating',
      type: 'indicator',
      inputs: 3,
      options: 1,
      outputs: 1,
      input_names: [ 'high', 'low', 'close' ],
      option_names: [ 'period' ],
      output_names: [ 'dx' ],
      indicator: [Function],
      start: [Function] },
   ao: 
    { name: 'ao',
      full_name: 'Awesome Oscillator',
      type: 'indicator',
      inputs: 2,
      options: 0,
      outputs: 1,
      input_names: [ 'high', 'low' ],
      option_names: [],
      output_names: [ 'ao' ],
      indicator: [Function],
      start: [Function] },
   apo: 
    { name: 'apo',
      full_name: 'Absolute Price Oscillator',
      type: 'indicator',
      inputs: 1,
      options: 2,
      outputs: 1,
      input_names: [ 'real' ],
      option_names: [ 'short period', 'long period' ],
      output_names: [ 'apo' ],
      indicator: [Function],
      start: [Function] },
   aroon: 
    { name: 'aroon',
      full_name: 'Aroon',
      type: 'indicator',
      inputs: 2,
      options: 1,
      outputs: 2,
      input_names: [ 'high', 'low' ],
      option_names: [ 'period' ],
      output_names: [ 'aroon_down', 'aroon_up' ],
      indicator: [Function],
      start: [Function] },
   aroonosc: 
    { name: 'aroonosc',
      full_name: 'Aroon Oscillator',
      type: 'indicator',
      inputs: 2,
      options: 1,
      outputs: 1,
      input_names: [ 'high', 'low' ],
      option_names: [ 'period' ],
      output_names: [ 'aroonosc' ],
      indicator: [Function],
      start: [Function] },
   asin: 
    { name: 'asin',
      full_name: 'Vector Arcsine',
      type: 'simple',
      inputs: 1,
      options: 0,
      outputs: 1,
      input_names: [ 'real' ],
      option_names: [],
      output_names: [ 'asin' ],
      indicator: [Function],
      start: [Function] },
   atan: 
    { name: 'atan',
      full_name: 'Vector Arctangent',
      type: 'simple',
      inputs: 1,
      options: 0,
      outputs: 1,
      input_names: [ 'real' ],
      option_names: [],
      output_names: [ 'atan' ],
      indicator: [Function],
      start: [Function] },
   atr: 
    { name: 'atr',
      full_name: 'Average True Range',
      type: 'indicator',
      inputs: 3,
      options: 1,
      outputs: 1,
      input_names: [ 'high', 'low', 'close' ],
      option_names: [ 'period' ],
      output_names: [ 'atr' ],
      indicator: [Function],
      start: [Function] },
   avgprice: 
    { name: 'avgprice',
      full_name: 'Average Price',
      type: 'overlay',
      inputs: 4,
      options: 0,
      outputs: 1,
      input_names: [ 'open', 'high', 'low', 'close' ],
      option_names: [],
      output_names: [ 'avgprice' ],
      indicator: [Function],
      start: [Function] },
   bbands: 
    { name: 'bbands',
      full_name: 'Bollinger Bands',
      type: 'overlay',
      inputs: 1,
      options: 2,
      outputs: 3,
      input_names: [ 'real' ],
      option_names: [ 'period', 'stddev' ],
      output_names: [ 'bbands_lower', 'bbands_middle', 'bbands_upper' ],
      indicator: [Function],
      start: [Function] },
   bop: 
    { name: 'bop',
      full_name: 'Balance of Power',
      type: 'indicator',
      inputs: 4,
      options: 0,
      outputs: 1,
      input_names: [ 'open', 'high', 'low', 'close' ],
      option_names: [],
      output_names: [ 'bop' ],
      indicator: [Function],
      start: [Function] },
   cci: 
    { name: 'cci',
      full_name: 'Commodity Channel Index',
      type: 'indicator',
      inputs: 3,
      options: 1,
      outputs: 1,
      input_names: [ 'high', 'low', 'close' ],
      option_names: [ 'period' ],
      output_names: [ 'cci' ],
      indicator: [Function],
      start: [Function] },
   ceil: 
    { name: 'ceil',
      full_name: 'Vector Ceiling',
      type: 'simple',
      inputs: 1,
      options: 0,
      outputs: 1,
      input_names: [ 'real' ],
      option_names: [],
      output_names: [ 'ceil' ],
      indicator: [Function],
      start: [Function] },
   cmo: 
    { name: 'cmo',
      full_name: 'Chande Momentum Oscillator',
      type: 'indicator',
      inputs: 1,
      options: 1,
      outputs: 1,
      input_names: [ 'real' ],
      option_names: [ 'period' ],
      output_names: [ 'cmo' ],
      indicator: [Function],
      start: [Function] },
   cos: 
    { name: 'cos',
      full_name: 'Vector Cosine',
      type: 'simple',
      inputs: 1,
      options: 0,
      outputs: 1,
      input_names: [ 'real' ],
      option_names: [],
      output_names: [ 'cos' ],
      indicator: [Function],
      start: [Function] },
   cosh: 
    { name: 'cosh',
      full_name: 'Vector Hyperbolic Cosine',
      type: 'simple',
      inputs: 1,
      options: 0,
      outputs: 1,
      input_names: [ 'real' ],
      option_names: [],
      output_names: [ 'cosh' ],
      indicator: [Function],
      start: [Function] },
   crossany: 
    { name: 'crossany',
      full_name: 'Crossany',
      type: 'math',
      inputs: 2,
      options: 0,
      outputs: 1,
      input_names: [ 'real', 'real' ],
      option_names: [],
      output_names: [ 'crossany' ],
      indicator: [Function],
      start: [Function] },
   crossover: 
    { name: 'crossover',
      full_name: 'Crossover',
      type: 'math',
      inputs: 2,
      options: 0,
      outputs: 1,
      input_names: [ 'real', 'real' ],
      option_names: [],
      output_names: [ 'crossover' ],
      indicator: [Function],
      start: [Function] },
   cvi: 
    { name: 'cvi',
      full_name: 'Chaikins Volatility',
      type: 'indicator',
      inputs: 2,
      options: 1,
      outputs: 1,
      input_names: [ 'high', 'low' ],
      option_names: [ 'period' ],
      output_names: [ 'cvi' ],
      indicator: [Function],
      start: [Function] },
   decay: 
    { name: 'decay',
      full_name: 'Linear Decay',
      type: 'math',
      inputs: 1,
      options: 1,
      outputs: 1,
      input_names: [ 'real' ],
      option_names: [ 'period' ],
      output_names: [ 'decay' ],
      indicator: [Function],
      start: [Function] },
   dema: 
    { name: 'dema',
      full_name: 'Double Exponential Moving Average',
      type: 'overlay',
      inputs: 1,
      options: 1,
      outputs: 1,
      input_names: [ 'real' ],
      option_names: [ 'period' ],
      output_names: [ 'dema' ],
      indicator: [Function],
      start: [Function] },
   di: 
    { name: 'di',
      full_name: 'Directional Indicator',
      type: 'indicator',
      inputs: 3,
      options: 1,
      outputs: 2,
      input_names: [ 'high', 'low', 'close' ],
      option_names: [ 'period' ],
      output_names: [ 'plus_di', 'minus_di' ],
      indicator: [Function],
      start: [Function] },
   div: 
    { name: 'div',
      full_name: 'Vector Division',
      type: 'simple',
      inputs: 2,
      options: 0,
      outputs: 1,
      input_names: [ 'real', 'real' ],
      option_names: [],
      output_names: [ 'div' ],
      indicator: [Function],
      start: [Function] },
   dm: 
    { name: 'dm',
      full_name: 'Directional Movement',
      type: 'indicator',
      inputs: 2,
      options: 1,
      outputs: 2,
      input_names: [ 'high', 'low' ],
      option_names: [ 'period' ],
      output_names: [ 'plus_dm', 'minus_dm' ],
      indicator: [Function],
      start: [Function] },
   dpo: 
    { name: 'dpo',
      full_name: 'Detrended Price Oscillator',
      type: 'indicator',
      inputs: 1,
      options: 1,
      outputs: 1,
      input_names: [ 'real' ],
      option_names: [ 'period' ],
      output_names: [ 'dpo' ],
      indicator: [Function],
      start: [Function] },
   dx: 
    { name: 'dx',
      full_name: 'Directional Movement Index',
      type: 'indicator',
      inputs: 3,
      options: 1,
      outputs: 1,
      input_names: [ 'high', 'low', 'close' ],
      option_names: [ 'period' ],
      output_names: [ 'dx' ],
      indicator: [Function],
      start: [Function] },
   edecay: 
    { name: 'edecay',
      full_name: 'Exponential Decay',
      type: 'math',
      inputs: 1,
      options: 1,
      outputs: 1,
      input_names: [ 'real' ],
      option_names: [ 'period' ],
      output_names: [ 'edecay' ],
      indicator: [Function],
      start: [Function] },
   ema: 
    { name: 'ema',
      full_name: 'Exponential Moving Average',
      type: 'overlay',
      inputs: 1,
      options: 1,
      outputs: 1,
      input_names: [ 'real' ],
      option_names: [ 'period' ],
      output_names: [ 'ema' ],
      indicator: [Function],
      start: [Function] },
   emv: 
    { name: 'emv',
      full_name: 'Ease of Movement',
      type: 'indicator',
      inputs: 3,
      options: 0,
      outputs: 1,
      input_names: [ 'high', 'low', 'volume' ],
      option_names: [],
      output_names: [ 'emv' ],
      indicator: [Function],
      start: [Function] },
   exp: 
    { name: 'exp',
      full_name: 'Vector Exponential',
      type: 'simple',
      inputs: 1,
      options: 0,
      outputs: 1,
      input_names: [ 'real' ],
      option_names: [],
      output_names: [ 'exp' ],
      indicator: [Function],
      start: [Function] },
   fisher: 
    { name: 'fisher',
      full_name: 'Fisher Transform',
      type: 'indicator',
      inputs: 2,
      options: 1,
      outputs: 2,
      input_names: [ 'high', 'low' ],
      option_names: [ 'period' ],
      output_names: [ 'fisher', 'fisher_signal' ],
      indicator: [Function],
      start: [Function] },
   floor: 
    { name: 'floor',
      full_name: 'Vector Floor',
      type: 'simple',
      inputs: 1,
      options: 0,
      outputs: 1,
      input_names: [ 'real' ],
      option_names: [],
      output_names: [ 'floor' ],
      indicator: [Function],
      start: [Function] },
   fosc: 
    { name: 'fosc',
      full_name: 'Forecast Oscillator',
      type: 'indicator',
      inputs: 1,
      options: 1,
      outputs: 1,
      input_names: [ 'real' ],
      option_names: [ 'period' ],
      output_names: [ 'fosc' ],
      indicator: [Function],
      start: [Function] },
   hma: 
    { name: 'hma',
      full_name: 'Hull Moving Average',
      type: 'overlay',
      inputs: 1,
      options: 1,
      outputs: 1,
      input_names: [ 'real' ],
      option_names: [ 'period' ],
      output_names: [ 'hma' ],
      indicator: [Function],
      start: [Function] },
   kama: 
    { name: 'kama',
      full_name: 'Kaufman Adaptive Moving Average',
      type: 'overlay',
      inputs: 1,
      options: 1,
      outputs: 1,
      input_names: [ 'real' ],
      option_names: [ 'period' ],
      output_names: [ 'kama' ],
      indicator: [Function],
      start: [Function] },
   kvo: 
    { name: 'kvo',
      full_name: 'Klinger Volume Oscillator',
      type: 'indicator',
      inputs: 4,
      options: 2,
      outputs: 1,
      input_names: [ 'high', 'low', 'close', 'volume' ],
      option_names: [ 'short period', 'long period' ],
      output_names: [ 'kvo' ],
      indicator: [Function],
      start: [Function] },
   lag: 
    { name: 'lag',
      full_name: 'Lag',
      type: 'math',
      inputs: 1,
      options: 1,
      outputs: 1,
      input_names: [ 'real' ],
      option_names: [ 'period' ],
      output_names: [ 'lag' ],
      indicator: [Function],
      start: [Function] },
   linreg: 
    { name: 'linreg',
      full_name: 'Linear Regression',
      type: 'overlay',
      inputs: 1,
      options: 1,
      outputs: 1,
      input_names: [ 'real' ],
      option_names: [ 'period' ],
      output_names: [ 'linreg' ],
      indicator: [Function],
      start: [Function] },
   linregintercept: 
    { name: 'linregintercept',
      full_name: 'Linear Regression Intercept',
      type: 'indicator',
      inputs: 1,
      options: 1,
      outputs: 1,
      input_names: [ 'real' ],
      option_names: [ 'period' ],
      output_names: [ 'linregintercept' ],
      indicator: [Function],
      start: [Function] },
   linregslope: 
    { name: 'linregslope',
      full_name: 'Linear Regression Slope',
      type: 'indicator',
      inputs: 1,
      options: 1,
      outputs: 1,
      input_names: [ 'real' ],
      option_names: [ 'period' ],
      output_names: [ 'linregslope' ],
      indicator: [Function],
      start: [Function] },
   ln: 
    { name: 'ln',
      full_name: 'Vector Natural Log',
      type: 'simple',
      inputs: 1,
      options: 0,
      outputs: 1,
      input_names: [ 'real' ],
      option_names: [],
      output_names: [ 'ln' ],
      indicator: [Function],
      start: [Function] },
   log10: 
    { name: 'log10',
      full_name: 'Vector Base-10 Log',
      type: 'simple',
      inputs: 1,
      options: 0,
      outputs: 1,
      input_names: [ 'real' ],
      option_names: [],
      output_names: [ 'log10' ],
      indicator: [Function],
      start: [Function] },
   macd: 
    { name: 'macd',
      full_name: 'Moving Average Convergence/Divergence',
      type: 'indicator',
      inputs: 1,
      options: 3,
      outputs: 3,
      input_names: [ 'real' ],
      option_names: [ 'short period', 'long period', 'signal period' ],
      output_names: [ 'macd', 'macd_signal', 'macd_histogram' ],
      indicator: [Function],
      start: [Function] },
   marketfi: 
    { name: 'marketfi',
      full_name: 'Market Facilitation Index',
      type: 'indicator',
      inputs: 3,
      options: 0,
      outputs: 1,
      input_names: [ 'high', 'low', 'volume' ],
      option_names: [],
      output_names: [ 'marketfi' ],
      indicator: [Function],
      start: [Function] },
   mass: 
    { name: 'mass',
      full_name: 'Mass Index',
      type: 'indicator',
      inputs: 2,
      options: 1,
      outputs: 1,
      input_names: [ 'high', 'low' ],
      option_names: [ 'period' ],
      output_names: [ 'mass' ],
      indicator: [Function],
      start: [Function] },
   max: 
    { name: 'max',
      full_name: 'Maximum In Period',
      type: 'math',
      inputs: 1,
      options: 1,
      outputs: 1,
      input_names: [ 'real' ],
      option_names: [ 'period' ],
      output_names: [ 'max' ],
      indicator: [Function],
      start: [Function] },
   md: 
    { name: 'md',
      full_name: 'Mean Deviation Over Period',
      type: 'math',
      inputs: 1,
      options: 1,
      outputs: 1,
      input_names: [ 'real' ],
      option_names: [ 'period' ],
      output_names: [ 'md' ],
      indicator: [Function],
      start: [Function] },
   medprice: 
    { name: 'medprice',
      full_name: 'Median Price',
      type: 'overlay',
      inputs: 2,
      options: 0,
      outputs: 1,
      input_names: [ 'high', 'low' ],
      option_names: [],
      output_names: [ 'medprice' ],
      indicator: [Function],
      start: [Function] },
   mfi: 
    { name: 'mfi',
      full_name: 'Money Flow Index',
      type: 'indicator',
      inputs: 4,
      options: 1,
      outputs: 1,
      input_names: [ 'high', 'low', 'close', 'volume' ],
      option_names: [ 'period' ],
      output_names: [ 'mfi' ],
      indicator: [Function],
      start: [Function] },
   min: 
    { name: 'min',
      full_name: 'Minimum In Period',
      type: 'math',
      inputs: 1,
      options: 1,
      outputs: 1,
      input_names: [ 'real' ],
      option_names: [ 'period' ],
      output_names: [ 'min' ],
      indicator: [Function],
      start: [Function] },
   mom: 
    { name: 'mom',
      full_name: 'Momentum',
      type: 'indicator',
      inputs: 1,
      options: 1,
      outputs: 1,
      input_names: [ 'real' ],
      option_names: [ 'period' ],
      output_names: [ 'mom' ],
      indicator: [Function],
      start: [Function] },
   msw: 
    { name: 'msw',
      full_name: 'Mesa Sine Wave',
      type: 'indicator',
      inputs: 1,
      options: 1,
      outputs: 2,
      input_names: [ 'real' ],
      option_names: [ 'period' ],
      output_names: [ 'msw_sine', 'msw_lead' ],
      indicator: [Function],
      start: [Function] },
   mul: 
    { name: 'mul',
      full_name: 'Vector Multiplication',
      type: 'simple',
      inputs: 2,
      options: 0,
      outputs: 1,
      input_names: [ 'real', 'real' ],
      option_names: [],
      output_names: [ 'mul' ],
      indicator: [Function],
      start: [Function] },
   natr: 
    { name: 'natr',
      full_name: 'Normalized Average True Range',
      type: 'indicator',
      inputs: 3,
      options: 1,
      outputs: 1,
      input_names: [ 'high', 'low', 'close' ],
      option_names: [ 'period' ],
      output_names: [ 'natr' ],
      indicator: [Function],
      start: [Function] },
   nvi: 
    { name: 'nvi',
      full_name: 'Negative Volume Index',
      type: 'indicator',
      inputs: 2,
      options: 0,
      outputs: 1,
      input_names: [ 'close', 'volume' ],
      option_names: [],
      output_names: [ 'nvi' ],
      indicator: [Function],
      start: [Function] },
   obv: 
    { name: 'obv',
      full_name: 'On Balance Volume',
      type: 'indicator',
      inputs: 2,
      options: 0,
      outputs: 1,
      input_names: [ 'close', 'volume' ],
      option_names: [],
      output_names: [ 'obv' ],
      indicator: [Function],
      start: [Function] },
   ppo: 
    { name: 'ppo',
      full_name: 'Percentage Price Oscillator',
      type: 'indicator',
      inputs: 1,
      options: 2,
      outputs: 1,
      input_names: [ 'real' ],
      option_names: [ 'short period', 'long period' ],
      output_names: [ 'ppo' ],
      indicator: [Function],
      start: [Function] },
   psar: 
    { name: 'psar',
      full_name: 'Parabolic SAR',
      type: 'overlay',
      inputs: 2,
      options: 2,
      outputs: 1,
      input_names: [ 'high', 'low' ],
      option_names: [ 'acceleration factor step', 'acceleration factor maximum' ],
      output_names: [ 'psar' ],
      indicator: [Function],
      start: [Function] },
   pvi: 
    { name: 'pvi',
      full_name: 'Positive Volume Index',
      type: 'indicator',
      inputs: 2,
      options: 0,
      outputs: 1,
      input_names: [ 'close', 'volume' ],
      option_names: [],
      output_names: [ 'pvi' ],
      indicator: [Function],
      start: [Function] },
   qstick: 
    { name: 'qstick',
      full_name: 'Qstick',
      type: 'indicator',
      inputs: 2,
      options: 1,
      outputs: 1,
      input_names: [ 'open', 'close' ],
      option_names: [ 'period' ],
      output_names: [ 'qstick' ],
      indicator: [Function],
      start: [Function] },
   roc: 
    { name: 'roc',
      full_name: 'Rate of Change',
      type: 'indicator',
      inputs: 1,
      options: 1,
      outputs: 1,
      input_names: [ 'real' ],
      option_names: [ 'period' ],
      output_names: [ 'roc' ],
      indicator: [Function],
      start: [Function] },
   rocr: 
    { name: 'rocr',
      full_name: 'Rate of Change Ratio',
      type: 'indicator',
      inputs: 1,
      options: 1,
      outputs: 1,
      input_names: [ 'real' ],
      option_names: [ 'period' ],
      output_names: [ 'rocr' ],
      indicator: [Function],
      start: [Function] },
   round: 
    { name: 'round',
      full_name: 'Vector Round',
      type: 'simple',
      inputs: 1,
      options: 0,
      outputs: 1,
      input_names: [ 'real' ],
      option_names: [],
      output_names: [ 'round' ],
      indicator: [Function],
      start: [Function] },
   rsi: 
    { name: 'rsi',
      full_name: 'Relative Strength Index',
      type: 'indicator',
      inputs: 1,
      options: 1,
      outputs: 1,
      input_names: [ 'real' ],
      option_names: [ 'period' ],
      output_names: [ 'rsi' ],
      indicator: [Function],
      start: [Function] },
   sin: 
    { name: 'sin',
      full_name: 'Vector Sine',
      type: 'simple',
      inputs: 1,
      options: 0,
      outputs: 1,
      input_names: [ 'real' ],
      option_names: [],
      output_names: [ 'sin' ],
      indicator: [Function],
      start: [Function] },
   sinh: 
    { name: 'sinh',
      full_name: 'Vector Hyperbolic Sine',
      type: 'simple',
      inputs: 1,
      options: 0,
      outputs: 1,
      input_names: [ 'real' ],
      option_names: [],
      output_names: [ 'sinh' ],
      indicator: [Function],
      start: [Function] },
   sma: 
    { name: 'sma',
      full_name: 'Simple Moving Average',
      type: 'overlay',
      inputs: 1,
      options: 1,
      outputs: 1,
      input_names: [ 'real' ],
      option_names: [ 'period' ],
      output_names: [ 'sma' ],
      indicator: [Function],
      start: [Function] },
   sqrt: 
    { name: 'sqrt',
      full_name: 'Vector Square Root',
      type: 'simple',
      inputs: 1,
      options: 0,
      outputs: 1,
      input_names: [ 'real' ],
      option_names: [],
      output_names: [ 'sqrt' ],
      indicator: [Function],
      start: [Function] },
   stddev: 
    { name: 'stddev',
      full_name: 'Standard Deviation Over Period',
      type: 'math',
      inputs: 1,
      options: 1,
      outputs: 1,
      input_names: [ 'real' ],
      option_names: [ 'period' ],
      output_names: [ 'stddev' ],
      indicator: [Function],
      start: [Function] },
   stderr: 
    { name: 'stderr',
      full_name: 'Standard Error Over Period',
      type: 'math',
      inputs: 1,
      options: 1,
      outputs: 1,
      input_names: [ 'real' ],
      option_names: [ 'period' ],
      output_names: [ 'stderr' ],
      indicator: [Function],
      start: [Function] },
   stoch: 
    { name: 'stoch',
      full_name: 'Stochastic Oscillator',
      type: 'indicator',
      inputs: 3,
      options: 3,
      outputs: 2,
      input_names: [ 'high', 'low', 'close' ],
      option_names: [ '%k period', '%k slowing period', '%d period' ],
      output_names: [ 'stoch_k', 'stoch_d' ],
      indicator: [Function],
      start: [Function] },
   sub: 
    { name: 'sub',
      full_name: 'Vector Subtraction',
      type: 'simple',
      inputs: 2,
      options: 0,
      outputs: 1,
      input_names: [ 'real', 'real' ],
      option_names: [],
      output_names: [ 'sub' ],
      indicator: [Function],
      start: [Function] },
   sum: 
    { name: 'sum',
      full_name: 'Sum Over Period',
      type: 'math',
      inputs: 1,
      options: 1,
      outputs: 1,
      input_names: [ 'real' ],
      option_names: [ 'period' ],
      output_names: [ 'sum' ],
      indicator: [Function],
      start: [Function] },
   tan: 
    { name: 'tan',
      full_name: 'Vector Tangent',
      type: 'simple',
      inputs: 1,
      options: 0,
      outputs: 1,
      input_names: [ 'real' ],
      option_names: [],
      output_names: [ 'tan' ],
      indicator: [Function],
      start: [Function] },
   tanh: 
    { name: 'tanh',
      full_name: 'Vector Hyperbolic Tangent',
      type: 'simple',
      inputs: 1,
      options: 0,
      outputs: 1,
      input_names: [ 'real' ],
      option_names: [],
      output_names: [ 'tanh' ],
      indicator: [Function],
      start: [Function] },
   tema: 
    { name: 'tema',
      full_name: 'Triple Exponential Moving Average',
      type: 'overlay',
      inputs: 1,
      options: 1,
      outputs: 1,
      input_names: [ 'real' ],
      option_names: [ 'period' ],
      output_names: [ 'tema' ],
      indicator: [Function],
      start: [Function] },
   todeg: 
    { name: 'todeg',
      full_name: 'Vector Degree Conversion',
      type: 'simple',
      inputs: 1,
      options: 0,
      outputs: 1,
      input_names: [ 'real' ],
      option_names: [],
      output_names: [ 'degrees' ],
      indicator: [Function],
      start: [Function] },
   torad: 
    { name: 'torad',
      full_name: 'Vector Radian Conversion',
      type: 'simple',
      inputs: 1,
      options: 0,
      outputs: 1,
      input_names: [ 'real' ],
      option_names: [],
      output_names: [ 'radians' ],
      indicator: [Function],
      start: [Function] },
   tr: 
    { name: 'tr',
      full_name: 'True Range',
      type: 'indicator',
      inputs: 3,
      options: 0,
      outputs: 1,
      input_names: [ 'high', 'low', 'close' ],
      option_names: [],
      output_names: [ 'tr' ],
      indicator: [Function],
      start: [Function] },
   trima: 
    { name: 'trima',
      full_name: 'Triangular Moving Average',
      type: 'overlay',
      inputs: 1,
      options: 1,
      outputs: 1,
      input_names: [ 'real' ],
      option_names: [ 'period' ],
      output_names: [ 'trima' ],
      indicator: [Function],
      start: [Function] },
   trix: 
    { name: 'trix',
      full_name: 'Trix',
      type: 'indicator',
      inputs: 1,
      options: 1,
      outputs: 1,
      input_names: [ 'real' ],
      option_names: [ 'period' ],
      output_names: [ 'trix' ],
      indicator: [Function],
      start: [Function] },
   trunc: 
    { name: 'trunc',
      full_name: 'Vector Truncate',
      type: 'simple',
      inputs: 1,
      options: 0,
      outputs: 1,
      input_names: [ 'real' ],
      option_names: [],
      output_names: [ 'trunc' ],
      indicator: [Function],
      start: [Function] },
   tsf: 
    { name: 'tsf',
      full_name: 'Time Series Forecast',
      type: 'overlay',
      inputs: 1,
      options: 1,
      outputs: 1,
      input_names: [ 'real' ],
      option_names: [ 'period' ],
      output_names: [ 'tsf' ],
      indicator: [Function],
      start: [Function] },
   typprice: 
    { name: 'typprice',
      full_name: 'Typical Price',
      type: 'overlay',
      inputs: 3,
      options: 0,
      outputs: 1,
      input_names: [ 'high', 'low', 'close' ],
      option_names: [],
      output_names: [ 'typprice' ],
      indicator: [Function],
      start: [Function] },
   ultosc: 
    { name: 'ultosc',
      full_name: 'Ultimate Oscillator',
      type: 'indicator',
      inputs: 3,
      options: 3,
      outputs: 1,
      input_names: [ 'high', 'low', 'close' ],
      option_names: [ 'short period', 'medium period', 'long period' ],
      output_names: [ 'ultosc' ],
      indicator: [Function],
      start: [Function] },
   var: 
    { name: 'var',
      full_name: 'Variance Over Period',
      type: 'math',
      inputs: 1,
      options: 1,
      outputs: 1,
      input_names: [ 'real' ],
      option_names: [ 'period' ],
      output_names: [ 'var' ],
      indicator: [Function],
      start: [Function] },
   vhf: 
    { name: 'vhf',
      full_name: 'Vertical Horizontal Filter',
      type: 'indicator',
      inputs: 1,
      options: 1,
      outputs: 1,
      input_names: [ 'real' ],
      option_names: [ 'period' ],
      output_names: [ 'vhf' ],
      indicator: [Function],
      start: [Function] },
   vidya: 
    { name: 'vidya',
      full_name: 'Variable Index Dynamic Average',
      type: 'overlay',
      inputs: 1,
      options: 3,
      outputs: 1,
      input_names: [ 'real' ],
      option_names: [ 'short period', 'long period', 'alpha' ],
      output_names: [ 'vidya' ],
      indicator: [Function],
      start: [Function] },
   volatility: 
    { name: 'volatility',
      full_name: 'Annualized Historical Volatility',
      type: 'indicator',
      inputs: 1,
      options: 1,
      outputs: 1,
      input_names: [ 'real' ],
      option_names: [ 'period' ],
      output_names: [ 'volatility' ],
      indicator: [Function],
      start: [Function] },
   vosc: 
    { name: 'vosc',
      full_name: 'Volume Oscillator',
      type: 'indicator',
      inputs: 1,
      options: 2,
      outputs: 1,
      input_names: [ 'volume' ],
      option_names: [ 'short period', 'long period' ],
      output_names: [ 'vosc' ],
      indicator: [Function],
      start: [Function] },
   vwma: 
    { name: 'vwma',
      full_name: 'Volume Weighted Moving Average',
      type: 'overlay',
      inputs: 2,
      options: 1,
      outputs: 1,
      input_names: [ 'close', 'volume' ],
      option_names: [ 'period' ],
      output_names: [ 'vwma' ],
      indicator: [Function],
      start: [Function] },
   wad: 
    { name: 'wad',
      full_name: 'Williams Accumulation/Distribution',
      type: 'indicator',
      inputs: 3,
      options: 0,
      outputs: 1,
      input_names: [ 'high', 'low', 'close' ],
      option_names: [],
      output_names: [ 'wad' ],
      indicator: [Function],
      start: [Function] },
   wcprice: 
    { name: 'wcprice',
      full_name: 'Weighted Close Price',
      type: 'overlay',
      inputs: 3,
      options: 0,
      outputs: 1,
      input_names: [ 'high', 'low', 'close' ],
      option_names: [],
      output_names: [ 'wcprice' ],
      indicator: [Function],
      start: [Function] },
   wilders: 
    { name: 'wilders',
      full_name: 'Wilders Smoothing',
      type: 'overlay',
      inputs: 1,
      options: 1,
      outputs: 1,
      input_names: [ 'real' ],
      option_names: [ 'period' ],
      output_names: [ 'wilders' ],
      indicator: [Function],
      start: [Function] },
   willr: 
    { name: 'willr',
      full_name: 'Williams %R',
      type: 'indicator',
      inputs: 3,
      options: 1,
      outputs: 1,
      input_names: [ 'high', 'low', 'close' ],
      option_names: [ 'period' ],
      output_names: [ 'willr' ],
      indicator: [Function],
      start: [Function] },
   wma: 
    { name: 'wma',
      full_name: 'Weighted Moving Average',
      type: 'overlay',
      inputs: 1,
      options: 1,
      outputs: 1,
      input_names: [ 'real' ],
      option_names: [ 'period' ],
      output_names: [ 'wma' ],
      indicator: [Function],
      start: [Function] },
   zlema: 
    { name: 'zlema',
      full_name: 'Zero-Lag Exponential Moving Average',
      type: 'overlay',
      inputs: 1,
      options: 1,
      outputs: 1,
      input_names: [ 'real' ],
      option_names: [ 'period' ],
      output_names: [ 'zlema' ],
      indicator: [Function],
      start: [Function] } }
}
*/